Signal pallet from scratch
gamedaoco/gamedao-protocol pull request #69
Opened 2022-07-29 00:30 UTC by vovacha

2022-07-29 09:14 UTC, vovacha commented
After the recent discussion, the Spending proposal logic should be changed.
- remove Failed proposal status -> should be finalized
- add funds reserving on proposal start
- transfer reserved funds at the end

I am switching PR to draft.

2022-08-04 10:26 UTC, vasylenko-yevhen requested changes

2022-08-04 10:26 UTC, vasylenko-yevhen commented on signal/src/lib.rs
> +		) -> Result<(), DispatchError> {
Here, if `old_deposit == deposit`, there is no need to perform any action.
But instead, it will create two additional operations.

2022-08-04 14:16 UTC, vasylenko-yevhen approved these changes
Good job! :+1:

2022-08-04 14:33 UTC, merged

2022-08-04 20:26 UTC, 2075 reviewed
good job 👌

2022-08-05 09:52 UTC, vovacha commented
Wrong target branch, changes reverted. New PR https://github.com/gamedaoco/gamedao-protocol/pull/79